version: "3.7"
services:
    app:
        build: .
        container_name: app
        ports:
            - 5000:5000
        volumes:
            - .:/app
        environment:
            FLASK_ENV: development
